### ISSUE TITLE
image title is not shown in overlay

### ISSUE THREAD

**Issue by blueamerican** [jonathanheilmann/ext-jh_magnificpopup#25]
jh_magnificpopup 0.6.1,
fluid styled content
with the constants:
styles.content.textmedia.linkWrap.lightboxEnabled = 1
styles.content.textmedia.linkWrap.lightboxCssClass = magnificpopup
styles.content.textmedia.linkWrap.lightboxRelAttribute = magnificpopup[{field:uid}]
plugin.tx_jhmagnificpopup.magnificpopup.support.user = .ce-textpic

**Comment by jonathanheilmann** [comment]
Thanks for reporting this issue.

I'm going to do some investigation and provide a fix soon. (Actually I've no developing environment running fluid_styled_content and I've to setup a new one...)

**Comment by blueamerican** [comment]
Hi Jonathan,

yes ok.

I think the problem is, that the title tag is missing in the a href (fluid styled content).

http://s623623302.online.de/freizeit-umgebung/

I can give you an account if you want.

Viele Grüße 

Markus Dübbert

 mailto:info@markusduebbert.de info@markusduebbert.de 

Ziegelhüttter Weg 46  57627 Hachenburg

Tel: +49 2662 5078103 

 http://www.markusduebbert.de/ www.markusduebbert.de

Web Entwicklung, TYPO3

Von: Jonathan Heilmann [mailto:notifications@github.com] 
Gesendet: Freitag, 3. Juni 2016 11:49
An: jonathanheilmann/ext-jh_magnificpopup ext-jh_magnificpopup@noreply.github.com
Cc: Markus blueamerican@web.de; Author author@noreply.github.com
Betreff: Re: [jonathanheilmann/ext-jh_magnificpopup] image title is not shown in overlay (#25)

Thanks for reporting this issue.

I'm going to do some investigation and provide a fix soon. (Actually I've no developing environment running fluid_styled_content and I've to setup a new one...)

**Comment by jonathanheilmann** [comment]
These line in your setup should do the trick:

setup:

```
lib.fluidContent.settings.media.popup.linkParams.ATagParams.dataWrap = class="{$styles.content.textmedia.linkWrap.lightboxCssClass}" rel="{$styles.content.textmedia.linkWrap.lightboxRelAttribute}" title="{file:current:title}"

```

**Comment by blueamerican** [comment]
Hi Jonathan,

vielen Dank!

Du kannst den Server auch erstmal weiter nutzen, wenn du magst.

Viele Grüße 

Markus Dübbert

 mailto:info@markusduebbert.de info@markusduebbert.de 

Ziegelhüttter Weg 46  57627 Hachenburg

Tel: +49 2662 5078103 

 http://www.markusduebbert.de/ www.markusduebbert.de

Web Entwicklung, TYPO3

Von: Jonathan Heilmann [mailto:notifications@github.com] 
Gesendet: Freitag, 3. Juni 2016 23:32
An: jonathanheilmann/ext-jh_magnificpopup ext-jh_magnificpopup@noreply.github.com
Cc: Markus blueamerican@web.de; Author author@noreply.github.com
Betreff: Re: [jonathanheilmann/ext-jh_magnificpopup] image title is not shown in overlay (#25)

These line in your setup should do the trick:

setup:

lib.fluidContent.settings.media.popup.linkParams.ATagParams.dataWrap = class="{$styles.content.textmedia.linkWrap.lightboxCssClass}" rel="{$styles.content.textmedia.linkWrap.lightboxRelAttribute}" title="{file:current:title}"
