### ISSUE TITLE
Open original Images instead of processed

### ISSUE THREAD

**Issue by timwendisch** [jonathanheilmann/ext-jh_magnificpopup#31]
I use often lightboxes in that way, that my content-creators can set up an Image on the page and define the output-size for the normal Web-View. But if the visitors click on the image (with Click-Enlarage activate) the "original" big Image shall be open in the lightbox.

Currently always the already processed Image is shown.

If you want to show the "original Image" you have to change the source-parameter for link-generating:

Actual:
tt_content.image.20.1.imageLinkWrap.enable.ifEmpty.typolink.parameter.data = file:current:link

New (for opening the original Images)
tt_content.image.20.1.imageLinkWrap.enable.ifEmpty.typolink.parameter.data = file:current:publicUrl
tt_content.image.20.1.imageLinkWrap.typolink.parameter.data = file:current:publicUrl

**Comment by jonathanheilmann** [comment]
Thanks for these lines.
I'll add this to the documentation in section "How to".
