### ISSUE TITLE
No language dependent image file references are used, still the reference from the default language is used

### ISSUE THREAD

**Issue by wenglor-IT** [jonathanheilmann/ext-jh_magnificpopup#37]
If you use the link-type "image", it is possible to insert a image file reference (from the FAL). 
Here you can also use the image metadata fields "title" and "description" to overwrite the labels. Thats all ok.

But in multilingual sites it's still used the image reference (and title / description) from the default language, that's not correct. If you want define for each language a different image/title/description (translated labels), this has NO impact. The different file referece/labels are saved in the backend but in the frontend there are ignored, always the image (labels) from the default language are shown... i think that's a bug.

The only workarround at the moment is, to translate the labels (meta information) of the image in the FAL.. Then make only in the default language a file reference and do not override the labels and use the original from FAL.
But in this way you habe NO chance to diplay a language dependent image....

For a language dependent image the bug have to be fixed :-)

Thanks.

**Comment by jonathanheilmann** [comment]
Thanks for reporting this issue.

I've attached a modified version, which should solve this issue. Could you please test it and leave some feedback?
I found no solution, to display the values of the original file reference. But when translating, the original values are adopted and my be modified.

[jh_magnificpopup_0.6.4-dev_201608091550.zip](https://github.com/jonathanheilmann/ext-jh_magnificpopup/files/409094/jh_magnificpopup_0.6.4-dev_201608091550.zip)

**Comment by wenglor-IT** [comment]
Hello Jonathan Heilmann,

sorry for the late feedback. I was in
holidays last weeks.... now I had time to test your development.

I installed your modified version, but
I get the following php issue:

Fatal error: Call to a member function getRecordOverlay()
on null in /DATA_WEB/www/website/typo3conf/ext/jh_magnificpopup/Classes/Controller/MagnificpopupController.php
on line 83

We use typo3 version 6.2.x

If you have further question, feel free
to contact me.

Thanks fpr modify it again.
Let me know the new version.

Best rregards 
Florian Frick

```
            Mit freundlichen Grüßen / Best regards    wenglor sensoric GmbH           i. A. Florian Frick, Staatl. gepr. Techniker            IT - Software / IT - Software           florian.frick@wenglor.com   Phone: +49 (0)7542 5399-752     Fax: +49 (0)7542 5399-989                                                                   www.wenglor.com             wenglor sensoric GmbH           wenglor Straße 3           88069 Tettnang          GERMANY                                                           Registergericht Ulm HRB-Nr. 630872          USt-IdNr. DE145372740           St.-Nr. 6102200708          Geschäftsführer: Dieter Baur, Fabian Baur, Rafael Baur                
```

Von:      
 Jonathan Heilmann notifications@github.com
An:      
 jonathanheilmann/ext-jh_magnificpopup
ext-jh_magnificpopup@noreply.github.com
Kopie:      
 wenglor-IT florian.frick@wenglor.com,
Author author@noreply.github.com
Datum:      
 09.08.2016 16:02
Betreff:    
   Re: [jonathanheilmann/ext-jh_magnificpopup]
No language dependent image file references are used, still the reference
from the default language is used (#37)

Thanks for reporting this issue.
I've attached a modified version, which should solve this
issue. Could you please test it and leave some feedback?
I found no solution, to display the values of the original file reference.
But when translating, the original values are adopted and my be modified.
jh_magnificpopup_0.6.4-dev_201608091550.zip
—
You are receiving this because you authored the thread.
Reply to this email directly, view
it on GitHub, or mute
the thread.

**Comment by jonathanheilmann** [comment]
This is related to an failed @inject of PageRepository. Please try to deactivate and activate the extension again. If this doesn't work, clearing the system cache should solve the issue.

**Comment by wenglor-IT** [comment]
Hello Jonathan
Heilmann,

i tested the new version again and cleared
all caches (+ PHP opcode cache) with the install tool. 
Now it works !!

Thank you for this bugfix !

```
            Mit freundlichen Grüßen / Best regards    wenglor sensoric GmbH           i. A. Florian Frick, Staatl. gepr. Techniker            IT - Software / IT - Software           florian.frick@wenglor.com   Phone: +49 (0)7542 5399-752     Fax: +49 (0)7542 5399-989                                                                   www.wenglor.com             wenglor sensoric GmbH           wenglor Straße 3           88069 Tettnang          GERMANY                                                           Registergericht Ulm HRB-Nr. 630872          USt-IdNr. DE145372740           St.-Nr. 6102200708          Geschäftsführer: Dieter Baur, Fabian Baur, Rafael Baur                
```

Von:      
 Jonathan Heilmann notifications@github.com
An:      
 jonathanheilmann/ext-jh_magnificpopup
ext-jh_magnificpopup@noreply.github.com
Kopie:      
 wenglor-IT florian.frick@wenglor.com,
Author author@noreply.github.com
Datum:      
 02.09.2016 16:09
Betreff:    
   Re: [jonathanheilmann/ext-jh_magnificpopup]
No language dependent image file references are used, still the reference
from the default language is used (#37)

This is related to an failed @inject
of PageRepository. Please try to deactivate and activate the extension
again. If this doesn't work, clearing the system cache should solve the
issue. 
—
You are receiving this because you authored the thread.
Reply to this email directly, view
it on GitHub, or mute
the thread.

**Comment by jonathanheilmann** [comment]
Thanks for feedback!

I'll push the updated extension to TER within the next few days.

**Comment by jonathanheilmann** [comment]
I've pushed version 0.6.4 to TER
