### ISSUE TITLE
"View raw" link under image

### ISSUE THREAD

**Issue by Gorli** [jonathanheilmann/ext-jh_magnificpopup#42]
Hello,

do you think it is possible (Sometime) to add the following option to your extension (as option)?

I have added it in the "Default.html" and tested.

Thank you very much

Goarli

```
image: {
 titleSrc: 'title',
```

```
image: {
 titleSrc: function(item) {
  return item.el.attr('title') + ' &middot; <a href="'+item.src+'" target="_blank">download</a>';
 },
```

Adds "view original image" link to caption that just opens image via default browser method.
http://codepen.io/dimsemenov/pen/qGIlh

**Comment by jonathanheilmann** [comment]
I think I'm not going to add this as option to the original template, as there are many possible options and it would blows up the default template.

An option could be to add some complete/working example templates, extending the [how to section in documentation](https://docs.typo3.org/typo3cms/extensions/jh_magnificpopup/HowTo/Index.html).
