### ISSUE TITLE
Does not work. Images still open in new window

### ISSUE THREAD

**Issue by Milliw** [jonathanheilmann/ext-jh_magnificpopup#43]
Hi!

Can´t get this extension to work in TYPO3 6.2.27.
Don´t get any JS errors.

Think it´s because image enlarge links in picture CE´s are like:
`<a target="thePicture" onclick="openPic('index.php?eID=tx_cms_showpic&amp;file=209&amp;md5=5705060e998318a81c320ab4b725ae876b584827&amp;parameters%5B0%5D=YTo0OntzOjU6IndpZHRoIjtzOjQ6IjEyMDAiO3M6NjoiaGVpZ2h0IjtzOjQ6IjYw&amp;parameters%5B1%5D=MG0iO3M6NzoiYm9keVRhZyI7czo0MToiPGJvZHkgc3R5bGU9Im1hcmdpbjowOyBi&amp;parameters%5B2%5D=YWNrZ3JvdW5kOiNmZmY7Ij4iO3M6NDoid3JhcCI7czozNzoiPGEgaHJlZj0iamF2&amp;parameters%5B3%5D=YXNjcmlwdDpjbG9zZSgpOyI%2BIHwgPC9hPiI7fQ%3D%3D','thePicture','width=898,height=600,status=0,menubar=0'); return false;" href="index.php?eID=tx_cms_showpic&amp;file=209&amp;md5=5705060e998318a81c320ab4b725ae876b584827&amp;parameters%5B0%5D=YTo0OntzOjU6IndpZHRoIjtzOjQ6IjEyMDAiO3M6NjoiaGVpZ2h0IjtzOjQ6IjYw&amp;parameters%5B1%5D=MG0iO3M6NzoiYm9keVRhZyI7czo0MToiPGJvZHkgc3R5bGU9Im1hcmdpbjowOyBi&amp;parameters%5B2%5D=YWNrZ3JvdW5kOiNmZmY7Ij4iO3M6NDoid3JhcCI7czozNzoiPGEgaHJlZj0iamF2&amp;parameters%5B3%5D=YXNjcmlwdDpjbG9zZSgpOyI%2BIHwgPC9hPiI7fQ%3D%3D"><img width="1280" border="0" height="855" alt="" src="fileadmin/_processed_/csm_Galerie_0000_ostnor5_42ed865651.jpg"></a>`

Can´t find anything to resolve this...

If using with plugin it works except linked images appear at top of the website content area. Like they are not getting hidden by JS or so.

**Comment by Milliw** [comment]
Solved it.

Like noticed on [https://jweiland.net/video-anleitungen/typo3/interessante-typo3-extensions/jh-magnificpopup.html](the jweiland tutorial video page) it´s also for TYPO3 Versions 6.2.?? necessary to enable "Lightbox click-enlarge rendering" in content constants.

Maybe this should be mentioned in the documentation.
Greetings

**Comment by CDRO** [comment]
@MarcoWilli you just saved my day :D

**Comment by Batman777** [comment]
Hi Marco,

it looks as if I do have the same problem. Typo3 6.2.31. 
Version 0.6.1 is alright. When updating to 0.6.4 it doesn't work any more.

styles.content.textmedia.linkWrap.lightboxEnabled = 1
in TS Constants does not help either :-( .. Do you have any idea?
I have the html files before and after updating. But I can't find the error.

P.S. Images in "news" Extension work !!

P.P.S.
After updating I have the following code (shortened due to diplay errors):
`
<script type="text/javascript">
function openPic(url, winName, winParams) {	//
			var theWindow = window.open(url, winName, winParams);
			if (theWindow)	{theWindow.focus();}
		}
</script>
`
and at the bottom

`<script type="text/javascript">
/*<![CDATA[*/
/*jh_magnificpopup-iframe-3*/

    $('.mfp-iframe-3').magnificPopup({
        type: 'iframe',
        tClose: 'Schließen (Esc)',
        tLoading: 'Laden...',
        disableOn: 0,
        mainClass: 'mfp-zoom-in',
        preloader: 1,
        closeOnContentClick: 0,
        closeOnBgClick: 1,
        closeBtnInside: 0,
        showCloseBtn: 1,
        enableEscapeKey: 1,
        modal: 0,
        alignTop: 0,
        fixedContentPos: 'auto',
        fixedBgPos: 'auto',
        overflowY: 'auto',
        removalDelay: 500,
        closeMarkup: '<button title="%title%" class="mfp-close"><i class="mfp-close-icn">&times;</i></button>',
    });


/*]]>*/
</script>`

**Comment by Batman777** [comment]
Oh maan .. now I got it!

styles.content.textmedia.linkWrap.lightboxEnabled = 1
=> Wrong

styles.content.imgtext.linkWrap.lightboxEnabled = 1
=> Right

:-)

Now it works .... soooo where is my next problem :-/ .. newsletter .......

**Comment by jonathanheilmann** [comment]
This issue should be resolved, if it's still there, please open a new issue.
