### ISSUE TITLE
Mixed Contet error

### ISSUE THREAD

**Issue by e-LUNATIC** [jonathanheilmann/ext-jh_magnificpopup#44]
Hi. My main page is reachable over "https" and the external lightbox link is normal "http" to a subdomain.
Then the following error appears:
This request has been blocked; the content must be served over HTTPS.

**Comment by jonathanheilmann** [comment]
Sorry for delay.
This is a security error thrown by your browser and not related to the extension. The only reasonable solution is, to fetch the external page via https.
