### ISSUE TITLE
In Inline-Content with option "closeBtnInside=True" the Close Button is NOT working with EDGE

### ISSUE THREAD

**Issue by wenglor-IT** [jonathanheilmann/ext-jh_magnificpopup#45]
In the following context, the "Close"-button isn't working:

- Display typ: "Inline Content"
- Link typ : "Text"
- Method: "Inline"
- Magnific Popup -> closeBrnInside : true

In this constellation, the "X" (and ESC) isn't working with EDGE Browser. Only the click on background triggers the close of the popup.
We are using Version 0.6.4  (T3 6.2.x)

**Comment by jonathanheilmann** [comment]
Do you have a non working example?

**Comment by wenglor-IT** [comment]
https://www.wenglor.com/index.php?id=1177&L=1

**Comment by jonathanheilmann** [comment]
This is an issue in chrome, too and is related to this ["bug"](https://github.com/dimsemenov/Magnific-Popup/issues/278), resolved in this [PR](https://github.com/dimsemenov/Magnific-Popup/pull/437), but sadly not merged in mfp yet.

But there is a workaround:
In Constant Editor set **closeMarkup** (plugin.tx_jhmagnificpopup.type.ajax.closeMarkup) to
`<button title="%title%" class="mfp-close"><i class="mfp-close-icn mfp-close">&times;</i></button>`
