### ISSUE TITLE
TYPO3 7.6.15 TS-Setup Changes

### ISSUE THREAD

**Issue by bechtlepri** [jonathanheilmann/ext-jh_magnificpopup#49]
Hey there,

I just had an issue where after an upgrade from TYPO3 LTS 6 to TYPO3 LTS 7 the jh_magnificpopup stopped working. Thought I write about here so you can check it out or maybe it helps some soul that's been stuck like me.

**As a side note:**
Weirdly enough EXT:news-FAL-elements were fine (beautiful lightbox showed up) but for normal CE and IRRE in EXT:news there was only openPic.

## I usually had those lines of TS-Setup to make it working (TYPO3 LTS 6)
```
tt_content.image.20.1.imageLinkWrap.JSwindow = 0
tt_content.image.20.1.imageLinkWrap.directImageLink = 1
```

-> This way it renders without openPic and with a direct link instead the very long show_pic-link in the <a>.

But that stopped working in TYPO3 7.
I needed much longer than I should have but here is how I resolved it:

## I changed my TS-Setup to the following:
```
tt_content.image.20.1.imageLinkWrap.JSwindow = 0
tt_content.image.20.default.1.imageLinkWrap.JSwindow = 0

tt_content.image.20.1.imageLinkWrap.directImageLink = 1
tt_content.image.20.default.1.imageLinkWrap.directImageLink = 1
```

Now the extension works again.
I found nothing about a needed change from .1 to .default anywhere.

Besides that - works like a charm, like it did in TYPO3 LTS 6.

**Comment by kevinlieser** [comment]
Thanks, got it running now.

**Comment by jonathanheilmann** [comment]
I'm not able to finde anything creating a `default` node in `tt_content.image.20`. Neither in EXT:bootstrap_package, nor EXT:fluid_styled_content nor EXT:css_styled_content.
Do you use any extension modifying `tt_content.image.20`?

**Comment by bechtlepri** [comment]
@jonathanheilmann 
I searched the full template (template analysis).
I found something coming from EXT:imagecycle (which this site uses).
Could be the culprit here.

EXT:imagecycle/static/tt_content/
```
    lib.tt_content_image_20 < tt_content.image.20
    ...
    tt_content.image.20 >
    tt_content.image.20 = CASE
    tt_content.image.20 {
         	key.field = tx_imagecycle_activate
         	default < lib.tt_content_image_20
         	1 < lib.imagecycle
    }
```
I will add that crucial information to the original issue, if you want.
The site is using EXT:imagecycle version 3.0.1

But why does adding a ".default" make a difference for EXT:jh_magnificpopup?
Or is that only the case because of the combination of these 2 extensions?
(that's something I can't find anywhere online)

**Comment by jonathanheilmann** [comment]
Sorry for my delayed reply.

This is related to the combination of those two extensions.
EXT:jh_magnficipopup uses the default TYPO3 configuration, but  EXT:imagecycle modifies them and moves the `.1` configuration to `.default`.

The only solution is to manually add your setup
```
tt_content.image.20.1.imageLinkWrap.JSwindow = 0
tt_content.image.20.default.1.imageLinkWrap.JSwindow = 0

tt_content.image.20.1.imageLinkWrap.directImageLink = 1
tt_content.image.20.default.1.imageLinkWrap.directImageLink = 1
```
I'll add this to the documentation within the next release.
