### ISSUE TITLE
Filter skips images when JumpURL enabled

### ISSUE THREAD

**Issue by gillima** [jonathanheilmann/ext-jh_magnificpopup#54]
When activating JumpURL using `config.jumpurl_enabled=1` the links are skipped by the extension filter.
Here is an example of a JumpURL image link:
```
<a href="testgallery/?jumpurl=fileadmin%2Fgallery%2FP1050941.JPG&amp;juHash=7e326c89af1971c5764975e041d0d8492895dc1a"><img src="fileadmin/_processed_/2/6/csm_P1050941_ae4f011de7.jpg" width="290" height="218"></a>
```

**Comment by jonathanheilmann** [comment]
Thats the intended functionality of the filter, as Magnific Popup is not able to show images from jumpurls in a lightbox.
To use the lightbox you need to disable jumpurls.

**Comment by gillima** [comment]
I did a workaround by using my own filter function which strips everything after '&' from the file extension before i check for know file types. With this modification the popup works perfectly even with jumpurl enabled:

```
var extension = file.substr((file.lastIndexOf('.')+1)); // Get extension of file
extension = extension.substr(0, (extension.lastIndexOf('&')));
switch (extension) {
```

**Comment by jonathanheilmann** [comment]
I'll add this to documentation's section `how to` as jumpURL is deprecated.
