### ISSUE TITLE
[BUG] plugin magnificpopup for content - Inline and content-reference partial not found

### ISSUE THREAD

**Issue by erredeco** [jonathanheilmann/ext-jh_magnificpopup#56]
TYPO3: 8.7.13
Magnificpopup: 1.0.0

Using "link" it works, while using "inline" or "content-reference" it throws an error:

```
Oops, an error occurred!
The Fluid template files 
"E:/Siti/xamppv7/htdocs/typo3.demo8/web/typo3conf/ext/jh_magnificpopup/Resources/Private/Partials/Magnificpopup/.html", 
"E:/Siti/xamppv7/htdocs/typo3.demo8/web/typo3conf/ext/jh_magnificpopup/Resources/Private/Partials/Magnificpopup/" 
could not be loaded.
```
I am not using custom partials for the plugin,I have just installed it.

**Comment by jonathanheilmann** [comment]
This error occurs, if the plugin configuration is not complete. In this case, the method (ajax or inline) has not been selected.
I've attached an updated extension version, catching this error.
Could you please give it a try and leave me some feedback?

[jh_magnificpopup_1.0.1-dev_201805082134.zip](https://github.com/jonathanheilmann/ext-jh_magnificpopup/files/1985389/jh_magnificpopup_1.0.1-dev_201805082134.zip)

**Comment by erredeco** [comment]
yeah now I have understood my mistake. The patch works fine. 

Suggestion wouldn't it be better to remove the "select" null option and just use the other two? for example using two radio buttons; I mean the empty option is useless, right? you either must have "ajax" or "inline"

**Comment by jonathanheilmann** [comment]
Thats a great idea I'm going to implement.

**Comment by TrueType** [comment]
So what now? Everyone installing 1.0 runs into this bug? I cannot see, where my plugin configuration is incomplete. And I cannot see the changes you made to fix it? What about this zip file in a composer world, but no commit on Github. No hotfix version on TER, either.

**Comment by jonathanheilmann** [comment]
Keep calm and friendly. I'm doing this in my free time and it's rare, as there is nearly no one who want's to sponsor development, this extension is not on first position of my todo list.

I've pushed the changes to branch v1.0.1 and will release the new fersion in a few days.

**Comment by jonathanheilmann** [comment]
Version 1.0.1 has been uploaded a few days ago to TER and resolves this issue.
