### ISSUE TITLE
Compatibility issue with Minifier for TYPO3

### ISSUE THREAD

**Issue by psingler** [jonathanheilmann/ext-jh_magnificpopup#64]
If the Minifier for TYPO3 (min) extension is active is not possible to have multiple Magnific Popup elements on the same page as there is a problem with a disappearing semicolon. Specifically the semicolon at the end of the magnificPopup()-Function (see: https://github.com/jonathanheilmann/ext-jh_magnificpopup/blob/master/Resources/Private/Partials/Magnificpopup/Inline.html).

**Comment by jonathanheilmann** [comment]
Which TYPO3 CMS version and extension version do you use?

**Comment by psingler** [comment]
TYPO3 CMS: 7.6.23
jh_magnificpopup: 1.0.1
min: 1.6.0

**Comment by jonathanheilmann** [comment]
Looks like it's an EXT:min bug: https://forge.typo3.org/issues/81785
