### ISSUE TITLE
Make jh_magnificpopup work with fluid styled content

### ISSUE THREAD

**Issue by erredeco** [jonathanheilmann/ext-jh_magnificpopup#8]
It could be sufficient (I only tested the "Default" configuration, no CE, no RTE) to add to the manual that the following TS Constants must be included:

```
styles.content.textmedia.linkWrap.lightboxEnabled = 1
styles.content.textmedia.linkWrap.lightboxCssClass = magnificpopup
styles.content.textmedia.linkWrap.lightboxRelAttribute = magnificpopup[{field:uid}]
plugin.tx_jhmagnificpopup.magnificpopup.support.user = .ce-textpic
```

**Comment by jonathanheilmann** [comment]
Thanks for sharing!

Support of fluid styled content is planed for version 0.6.0

see https://forge.typo3.org/issues/73584 and https://forge.typo3.org/issues/73664

**Comment by blueamerican** [comment]
this works with fluid_styled_content but i miss the title in the overlay. this does not work

**Comment by erredeco** [comment]
@blueamerican I think that the commit  2bda635 (version 6.2 already on TER) solves the title issue
